### ISSUE TITLE
Store registry keys and files to evaluate externally via TOML, JSON, YAML, etc.

### ISSUE THREAD

**Issue by atc0005** [atc0005/check-restart#43]
From https://peps.python.org/pep-0621/#example:

<details>
<summary>pep-0621 TOML exmaple</summary>

```toml
[project]
name = "spam"
version = "2020.0.0"
description = "Lovely Spam! Wonderful Spam!"
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
keywords = ["egg", "bacon", "sausage", "tomatoes", "Lobster Thermidor"]
authors = [
  {email = "hi@pradyunsg.me"},
  {name = "Tzu-Ping Chung"}
]
maintainers = [
  {name = "Brett Cannon", email = "brett@python.org"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

dependencies = [
  "httpx",
  "gidgethub[httpx]>4.0.0",
  "django>2.1; os_name != 'nt'",
  "django>2.0; os_name == 'nt'"
]

[project.optional-dependencies]
test = [
  "pytest < 5.0.0",
  "pytest-cov[all]"
]

[project.urls]
homepage = "https://example.com"
documentation = "https://readthedocs.org"
repository = "https://github.com"
changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]
spam-cli = "spam:main_cli"

[project.gui-scripts]
spam-gui = "spam:main_gui"

[project.entry-points."spam.magical"]
tomatoes = "spam:main_tomatoes"
```

</details>

Does `[project.gui-scripts]` indicate a subsection named `gui-scripts` within `project` ?

Stumbled across this while reading a Dependabot change for Python projects. Wondering if this would be useful in externally specifying registry keys and files to evaluate.

Regardless of which format is chosen, the goal is to easily specify nested values.
